### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Bluscream** [exp111/pyTSon-Scripts#1]
great work on the nox plugin, never got around actually porting it from LUA to pyTSon (i had too many ideas for it so it became unrealistic to me)
Mind me replacing the one in my repo with yours (with you as the author ofc)?

**Comment by exp111** [comment]
Yea sure I don‘t really use the pytson nox as i ported it (again) to c++. 
I mean you wrote the base so it‘s mostly yours^^

**Comment by Bluscream** [comment]
Thank you :)

**Comment by Bluscream** [comment]
wtf xD
![](https://i.imgur.com/vw9jSa9.png)

**Comment by exp111** [comment]
Mhhh weird…
Does it work like that? (Shouldn‘t but I remember that feature working)
Else try the ts3lib.getCurrentServerConnectionHandler() function as we don’t care about multiple tabs

**Comment by Bluscream** [comment]
I know how pytson works xD
